### ISSUE TITLE
Could not load plugin

### ISSUE THREAD

**Issue by adrianlegaspi** [ToberoCat/ImprovedFaction#1]
I'm using BETA 4.0.0

[21:55:44 ERROR]: Could not load 'plugins\ImprovedFactions-BETAv4.0.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'ImprovedFactions'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:290) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:422) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-152]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
Steps to replicate:
  1. Place the plugin on the `/plugin` path
  2. Run the server
  3. The error will be prompted and the plugin will not be available in game
![d432803eadbca0436376930b7a249e48
![35fb42938df01f8fe5b398c1fae261b4](https://user-images.githubusercontent.com/15187610/152630748-10dc5e91-2b1e-45fa-93b4-a1559cf88747.png)
](https://user-images.githubusercontent.com/15187610/152630739-7d4be604-8d5e-48ba-8777-21ee44d739df.png)

**Comment by ToberoCat** [comment]
Did you install protocolLib?

**Comment by adrianlegaspi** [comment]
My bad, installed ProtocolLib and now it's working!

**Comment by ToberoCat** [comment]
Alright. No problem
